# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(762, 495)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dir_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dir_btn.setGeometry(QtCore.QRect(10, 0, 191, 28))
        self.dir_btn.setObjectName("dir_btn")
        self.images_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.images_list.setGeometry(QtCore.QRect(10, 30, 191, 411))
        self.images_list.setObjectName("images_list")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(250, 0, 495, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.left_btn.setObjectName("left_btn")
        self.horizontalLayout.addWidget(self.left_btn)
        self.right_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.right_btn.setObjectName("right_btn")
        self.horizontalLayout.addWidget(self.right_btn)
        self.mirror_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.mirror_btn.setObjectName("mirror_btn")
        self.horizontalLayout.addWidget(self.mirror_btn)
        self.sharp_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sharp_btn.setObjectName("sharp_btn")
        self.horizontalLayout.addWidget(self.sharp_btn)
        self.bw_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.bw_btn.setObjectName("bw_btn")
        self.horizontalLayout.addWidget(self.bw_btn)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 541, 391))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background: lightgrey;\n"
"border: 1px solid red;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dir_btn.setText(_translate("MainWindow", "папка"))
        self.left_btn.setText(_translate("MainWindow", "лево"))
        self.right_btn.setText(_translate("MainWindow", "право"))
        self.mirror_btn.setText(_translate("MainWindow", "дзерк"))
        self.sharp_btn.setText(_translate("MainWindow", "різкісьть"))
        self.bw_btn.setText(_translate("MainWindow", "ЧБ"))
        self.label.setText(_translate("MainWindow", "картинка"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
